# Generated by Django 4.2.17 on 2024-12-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_filiere_alter_cours_options_classe_filiere'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='classe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_room', to='school.classe'),
        ),
    ]
